# Use a imagem base do Node.js
FROM node:latest

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia o package.json e o yarn.lock para o diretório de trabalho
COPY package.json yarn.lock ./

# Instala as dependências
RUN yarn install

# Copia todos os arquivos do projeto para o diretório de trabalho
COPY . .

# Compila o projeto (se necessário)
RUN yarn run build

# Expõe a porta 80
EXPOSE 80

# Comando para iniciar a aplicação
CMD ["yarn", "start"]
